name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build @cartable/core
        run: pnpm --filter @cartable/core build

      - name: Build examples
        run: pnpm --filter "cartable-example-*" build

      - name: Test examples
        run: pnpm --filter "cartable-example-*" test
