name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.1

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build @cartable/core
        run: pnpm run build --filter @cartable/core

      - name: Build @cartable/create
        run: pnpm run build --filter @cartable/create

      - name: Build examples
        run: pnpm run build --filter "cartable-example-*"

      - name: Test examples
        run: pnpm run test --filter "cartable-example-*"
